### ISSUE TITLE
Nice project - any instructions on setup?

### ISSUE THREAD

**Issue by bartonhammond** [jon49/cash#1]
Hi - I've been looking for a PB w/ Javascript extension and found your project.  I like what you've done.  I'd like to run it locally but don't know what steps to do.  

Thanks for making this public - it's nicely done!

**Comment by jon49** [comment]
Sure, I'm just about done working on it. I need to add a few more tests for my html-form integration and then it should be mostly complete. It is an MPA that will work without JS and progressively enhanced by adding in  some JS (like above) and then I just added partial offline support.

Tomorrow I'll work on the docs rather than finishing up those tests. It might take me a day or two to get the docs up as I'm working on other stuff around the house during the break.

I'll let you know when I have the docs up!

**Comment by jon49** [comment]
OK, I added a README.md.

lol, I actually went to your repo for a todo app for pocketpages when I first started out looking into building an HTML first application. Unfortunately, I couldn't get pocketpages working as it is still alpha software. But Go HTML templates aren't all that bad.

**Comment by jon49** [comment]
Done.

**Comment by bartonhammond** [comment]
About pocketpages - i thought it had some hope but I think the author isn't getting enough traction and might have stopped development.

**Comment by jon49** [comment]
Yeah, he runs https://pockethost.io/ so I'm guessing he has a lot on his plate and the original version is working for him so he just has the newer version on the back plate. I don't think the older version works with the latest pocketbase code though, as I couldn't get either to work.
